### ISSUE TITLE
test failures on s390x

### ISSUE THREAD

**Issue by rathann** [WebAssembly/wabt#1670]
I'm getting new test failures with 1.0.23 on s390x running Fedora 34. The failing tests are:
```
- test/spec/simd/simd_load16_lane.txt
- test/spec/simd/simd_load32_lane.txt
- test/spec/simd/simd_load64_lane.txt
- test/spec/simd/simd_load8_lane.txt
- test/spec/simd/simd_store16_lane.txt
- test/spec/simd/simd_store32_lane.txt
- test/spec/simd/simd_store64_lane.txt
- test/spec/simd/simd_store8_lane.txt
```

Here's the log excerpt:

```
[...]
+ test/spec/simd/simd_i8x16_sat_arith.txt (0.022s)
- test/spec/simd/simd_load16_lane.txt
  expected error code 0, got 8.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,75 @@
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 0 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 1 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 2 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 3 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 4 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 5 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 6 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in lane 7 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:105: mismatch in result 0 of assert_return: expected v128 i16:0i16:0i16:0i16:0i16:0i16:0i16:0i16:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x01000000
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 0 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 1 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 2 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 3 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 4 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 5 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 6 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in lane 7 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:126: mismatch in result 0 of assert_return: expected v128 i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055, got v128 i32x4:0x00000807 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 0 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 1 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 2 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 3 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 4 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 5 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 6 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in lane 7 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:129: mismatch in result 0 of assert_return: expected v128 i16:0i16:0i16:0i16:0i16:0i16:0i16:0i16:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x01000000
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 0 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 1 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 2 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 3 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 4 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 5 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 6 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in lane 7 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:143: mismatch in result 0 of assert_return: expected v128 i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055, got v128 i32x4:0x00000807 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 0 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 1 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 2 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 3 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 4 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 5 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 6 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in lane 7 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:145: mismatch in result 0 of assert_return: expected v128 i16:0i16:0i16:0i16:0i16:0i16:0i16:0i16:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x01000000
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 0 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 1 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 2 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 3 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 4 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 5 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 6 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in lane 7 of result 0 of assert_return: expected i16:0, got i16:256
  +out/test/spec/simd/simd_load16_lane.wast:148: mismatch in result 0 of assert_return: expected v128 i16:0i16:0i16:0i16:0i16:0i16:0i16:0i16:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x01000000
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 0 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 1 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 2 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 3 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 4 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 5 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 6 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in lane 7 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:187: mismatch in result 0 of assert_return: expected v128 i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055, got v128 i32x4:0x00000807 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 0 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 1 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 2 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 3 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 4 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 5 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 6 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in lane 7 of result 0 of assert_return: expected i16:2055, got i16:0
  +out/test/spec/simd/simd_load16_lane.wast:190: mismatch in result 0 of assert_return: expected v128 i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055i16:2055, got v128 i32x4:0x00000807 0x00000000 0x00000000 0x00000000
   out/test/spec/simd/simd_load16_lane.wast:195: assert_invalid passed:
     error: type mismatch in v128.load16_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdLoadLaneExpr callback failed
  @@ -7,4 +79,4 @@
   out/test/spec/simd/simd_load16_lane.wast:208: assert_invalid passed:
     error: alignment must not be larger than natural alignment (2)
     0000027: error: OnSimdLoadLaneExpr callback failed
  -35/35 tests passed.
  +27/35 tests passed.
+ test/spec/simd/simd_lane.txt (0.032s)
+ test/spec/simd/simd_load.txt (0.024s)
- test/spec/simd/simd_load32_lane.txt
  expected error code 0, got 10.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,53 @@
  +out/test/spec/simd/simd_load32_lane.wast:69: mismatch in lane 0 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:69: mismatch in lane 1 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:69: mismatch in lane 2 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:69: mismatch in lane 3 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:69: mismatch in result 0 of assert_return: expected v128 i32:0i32:0i32:0i32:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x03020100
  +out/test/spec/simd/simd_load32_lane.wast:78: mismatch in lane 0 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:78: mismatch in lane 1 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:78: mismatch in lane 2 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:78: mismatch in lane 3 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:78: mismatch in result 0 of assert_return: expected v128 i32:100992003i32:100992003i32:100992003i32:100992003, got v128 i32x4:0x06050403 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load32_lane.wast:81: mismatch in lane 0 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:81: mismatch in lane 1 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:81: mismatch in lane 2 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:81: mismatch in lane 3 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:81: mismatch in result 0 of assert_return: expected v128 i32:0i32:0i32:0i32:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x03020100
  +out/test/spec/simd/simd_load32_lane.wast:87: mismatch in lane 0 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:87: mismatch in lane 1 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:87: mismatch in lane 2 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:87: mismatch in lane 3 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:87: mismatch in result 0 of assert_return: expected v128 i32:100992003i32:100992003i32:100992003i32:100992003, got v128 i32x4:0x06050403 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load32_lane.wast:89: mismatch in lane 0 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:89: mismatch in lane 1 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:89: mismatch in lane 2 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:89: mismatch in lane 3 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:89: mismatch in result 0 of assert_return: expected v128 i32:0i32:0i32:0i32:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x03020100
  +out/test/spec/simd/simd_load32_lane.wast:92: mismatch in lane 0 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:92: mismatch in lane 1 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:92: mismatch in lane 2 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:92: mismatch in lane 3 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:92: mismatch in result 0 of assert_return: expected v128 i32:0i32:0i32:0i32:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x03020100
  +out/test/spec/simd/simd_load32_lane.wast:95: mismatch in lane 0 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:95: mismatch in lane 1 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:95: mismatch in lane 2 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:95: mismatch in lane 3 of result 0 of assert_return: expected i32:0, got i32:50462976
  +out/test/spec/simd/simd_load32_lane.wast:95: mismatch in result 0 of assert_return: expected v128 i32:0i32:0i32:0i32:0, got v128 i32x4:0x00000000 0x00000000 0x00000000 0x03020100
  +out/test/spec/simd/simd_load32_lane.wast:116: mismatch in lane 0 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:116: mismatch in lane 1 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:116: mismatch in lane 2 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:116: mismatch in lane 3 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:116: mismatch in result 0 of assert_return: expected v128 i32:100992003i32:100992003i32:100992003i32:100992003, got v128 i32x4:0x06050403 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load32_lane.wast:119: mismatch in lane 0 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:119: mismatch in lane 1 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:119: mismatch in lane 2 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:119: mismatch in lane 3 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:119: mismatch in result 0 of assert_return: expected v128 i32:100992003i32:100992003i32:100992003i32:100992003, got v128 i32x4:0x06050403 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load32_lane.wast:122: mismatch in lane 0 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:122: mismatch in lane 1 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:122: mismatch in lane 2 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:122: mismatch in lane 3 of result 0 of assert_return: expected i32:100992003, got i32:0
  +out/test/spec/simd/simd_load32_lane.wast:122: mismatch in result 0 of assert_return: expected v128 i32:100992003i32:100992003i32:100992003i32:100992003, got v128 i32x4:0x06050403 0x00000000 0x00000000 0x00000000
   out/test/spec/simd/simd_load32_lane.wast:127: assert_invalid passed:
     error: type mismatch in v128.load32_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdLoadLaneExpr callback failed
  @@ -7,4 +57,4 @@
   out/test/spec/simd/simd_load32_lane.wast:140: assert_invalid passed:
     error: alignment must not be larger than natural alignment (4)
     0000027: error: OnSimdLoadLaneExpr callback failed
  -23/23 tests passed.
  +13/23 tests passed.
- test/spec/simd/simd_load64_lane.txt
  expected error code 0, got 12.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,39 @@
  +out/test/spec/simd/simd_load64_lane.wast:45: mismatch in lane 0 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:45: mismatch in lane 1 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:45: mismatch in result 0 of assert_return: expected v128 i64:0i64:0, got v128 i32x4:0x00000000 0x00000000 0x03020100 0x07060504
  +out/test/spec/simd/simd_load64_lane.wast:48: mismatch in lane 0 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:48: mismatch in lane 1 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:48: mismatch in result 0 of assert_return: expected v128 i64:578437695752307201i64:578437695752307201, got v128 i32x4:0x04030201 0x08070605 0x00000000 0x00000000
  +out/test/spec/simd/simd_load64_lane.wast:51: mismatch in lane 0 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:51: mismatch in lane 1 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:51: mismatch in result 0 of assert_return: expected v128 i64:0i64:0, got v128 i32x4:0x00000000 0x00000000 0x03020100 0x07060504
  +out/test/spec/simd/simd_load64_lane.wast:53: mismatch in lane 0 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:53: mismatch in lane 1 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:53: mismatch in result 0 of assert_return: expected v128 i64:578437695752307201i64:578437695752307201, got v128 i32x4:0x04030201 0x08070605 0x00000000 0x00000000
  +out/test/spec/simd/simd_load64_lane.wast:55: mismatch in lane 0 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:55: mismatch in lane 1 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:55: mismatch in result 0 of assert_return: expected v128 i64:0i64:0, got v128 i32x4:0x00000000 0x00000000 0x03020100 0x07060504
  +out/test/spec/simd/simd_load64_lane.wast:58: mismatch in lane 0 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:58: mismatch in lane 1 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:58: mismatch in result 0 of assert_return: expected v128 i64:0i64:0, got v128 i32x4:0x00000000 0x00000000 0x03020100 0x07060504
  +out/test/spec/simd/simd_load64_lane.wast:61: mismatch in lane 0 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:61: mismatch in lane 1 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:61: mismatch in result 0 of assert_return: expected v128 i64:0i64:0, got v128 i32x4:0x00000000 0x00000000 0x03020100 0x07060504
  +out/test/spec/simd/simd_load64_lane.wast:64: mismatch in lane 0 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:64: mismatch in lane 1 of result 0 of assert_return: expected i64:0, got i64:506097522914230528
  +out/test/spec/simd/simd_load64_lane.wast:64: mismatch in result 0 of assert_return: expected v128 i64:0i64:0, got v128 i32x4:0x00000000 0x00000000 0x03020100 0x07060504
  +out/test/spec/simd/simd_load64_lane.wast:67: mismatch in lane 0 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:67: mismatch in lane 1 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:67: mismatch in result 0 of assert_return: expected v128 i64:578437695752307201i64:578437695752307201, got v128 i32x4:0x04030201 0x08070605 0x00000000 0x00000000
  +out/test/spec/simd/simd_load64_lane.wast:70: mismatch in lane 0 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:70: mismatch in lane 1 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:70: mismatch in result 0 of assert_return: expected v128 i64:578437695752307201i64:578437695752307201, got v128 i32x4:0x04030201 0x08070605 0x00000000 0x00000000
  +out/test/spec/simd/simd_load64_lane.wast:73: mismatch in lane 0 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:73: mismatch in lane 1 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:73: mismatch in result 0 of assert_return: expected v128 i64:578437695752307201i64:578437695752307201, got v128 i32x4:0x04030201 0x08070605 0x00000000 0x00000000
  +out/test/spec/simd/simd_load64_lane.wast:76: mismatch in lane 0 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:76: mismatch in lane 1 of result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_load64_lane.wast:76: mismatch in result 0 of assert_return: expected v128 i64:578437695752307201i64:578437695752307201, got v128 i32x4:0x04030201 0x08070605 0x00000000 0x00000000
   out/test/spec/simd/simd_load64_lane.wast:81: assert_invalid passed:
     error: type mismatch in v128.load64_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdLoadLaneExpr callback failed
  @@ -7,4 +43,4 @@
   out/test/spec/simd/simd_load64_lane.wast:94: assert_invalid passed:
     error: alignment must not be larger than natural alignment (8)
     0000027: error: OnSimdLoadLaneExpr callback failed
  -15/15 tests passed.
  +3/15 tests passed.
- test/spec/simd/simd_load8_lane.txt
  expected error code 0, got 3.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,54 @@
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 0 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 1 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 2 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 3 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 4 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 5 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 6 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 7 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 8 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 9 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 10 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 11 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 12 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 13 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 14 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in lane 15 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:198: mismatch in result 0 of assert_return: expected v128 i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15, got v128 i32x4:0x0000000f 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 0 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 1 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 2 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 3 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 4 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 5 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 6 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 7 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 8 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 9 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 10 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 11 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 12 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 13 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 14 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in lane 15 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:231: mismatch in result 0 of assert_return: expected v128 i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15, got v128 i32x4:0x0000000f 0x00000000 0x00000000 0x00000000
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 0 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 1 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 2 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 3 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 4 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 5 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 6 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 7 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 8 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 9 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 10 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 11 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 12 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 13 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 14 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in lane 15 of result 0 of assert_return: expected i8:15, got i8:0
  +out/test/spec/simd/simd_load8_lane.wast:278: mismatch in result 0 of assert_return: expected v128 i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15i8:15, got v128 i32x4:0x0000000f 0x00000000 0x00000000 0x00000000
   out/test/spec/simd/simd_load8_lane.wast:283: assert_invalid passed:
     error: type mismatch in v128.load8_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdLoadLaneExpr callback failed
  @@ -7,4 +58,4 @@
   out/test/spec/simd/simd_load8_lane.wast:296: assert_invalid passed:
     error: alignment must not be larger than natural alignment (1)
     0000027: error: OnSimdLoadLaneExpr callback failed
  -51/51 tests passed.
  +48/51 tests passed.
+ test/spec/simd/simd_load_extend.txt (0.015s)
+ test/spec/simd/simd_load_splat.txt (0.015s)
+ test/spec/simd/simd_load_zero.txt (0.016s)
+ test/spec/simd/simd_splat.txt (0.021s)
+ test/spec/simd/simd_store.txt (0.016s)
- test/spec/simd/simd_store16_lane.txt
  expected error code 0, got 32.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,35 @@
  +out/test/spec/simd/simd_store16_lane.wast:193: mismatch in result 0 of assert_return: expected i64:256, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:196: mismatch in result 0 of assert_return: expected i64:513, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:199: mismatch in result 0 of assert_return: expected i64:770, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:202: mismatch in result 0 of assert_return: expected i64:1027, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:205: mismatch in result 0 of assert_return: expected i64:1284, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:208: mismatch in result 0 of assert_return: expected i64:1541, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:211: mismatch in result 0 of assert_return: expected i64:1798, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:214: mismatch in result 0 of assert_return: expected i64:2055, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:217: mismatch in result 0 of assert_return: expected i64:256, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:219: mismatch in result 0 of assert_return: expected i64:513, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:221: mismatch in result 0 of assert_return: expected i64:770, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:223: mismatch in result 0 of assert_return: expected i64:1027, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:225: mismatch in result 0 of assert_return: expected i64:1284, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:227: mismatch in result 0 of assert_return: expected i64:1541, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:229: mismatch in result 0 of assert_return: expected i64:1798, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:231: mismatch in result 0 of assert_return: expected i64:2055, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:233: mismatch in result 0 of assert_return: expected i64:256, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:236: mismatch in result 0 of assert_return: expected i64:256, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:239: mismatch in result 0 of assert_return: expected i64:513, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:242: mismatch in result 0 of assert_return: expected i64:513, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:245: mismatch in result 0 of assert_return: expected i64:770, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:248: mismatch in result 0 of assert_return: expected i64:770, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:251: mismatch in result 0 of assert_return: expected i64:1027, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:254: mismatch in result 0 of assert_return: expected i64:1027, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:257: mismatch in result 0 of assert_return: expected i64:1284, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:260: mismatch in result 0 of assert_return: expected i64:1284, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:263: mismatch in result 0 of assert_return: expected i64:1541, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:266: mismatch in result 0 of assert_return: expected i64:1541, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:269: mismatch in result 0 of assert_return: expected i64:1798, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:272: mismatch in result 0 of assert_return: expected i64:1798, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:275: mismatch in result 0 of assert_return: expected i64:2055, got i64:0
  +out/test/spec/simd/simd_store16_lane.wast:278: mismatch in result 0 of assert_return: expected i64:2055, got i64:0
   out/test/spec/simd/simd_store16_lane.wast:283: assert_invalid passed:
     error: type mismatch in v128.store16_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdStoreLaneExpr callback failed
  @@ -7,4 +39,4 @@
   out/test/spec/simd/simd_store16_lane.wast:296: assert_invalid passed:
     error: alignment must not be larger than natural alignment (2)
     0000027: error: OnSimdStoreLaneExpr callback failed
  -35/35 tests passed.
  +3/35 tests passed.
- test/spec/simd/simd_store32_lane.txt
  expected error code 0, got 20.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,23 @@
  +out/test/spec/simd/simd_store32_lane.wast:125: mismatch in result 0 of assert_return: expected i64:50462976, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:128: mismatch in result 0 of assert_return: expected i64:67305985, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:131: mismatch in result 0 of assert_return: expected i64:84148994, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:134: mismatch in result 0 of assert_return: expected i64:100992003, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:137: mismatch in result 0 of assert_return: expected i64:50462976, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:139: mismatch in result 0 of assert_return: expected i64:67305985, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:141: mismatch in result 0 of assert_return: expected i64:84148994, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:143: mismatch in result 0 of assert_return: expected i64:100992003, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:145: mismatch in result 0 of assert_return: expected i64:50462976, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:148: mismatch in result 0 of assert_return: expected i64:50462976, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:151: mismatch in result 0 of assert_return: expected i64:50462976, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:154: mismatch in result 0 of assert_return: expected i64:67305985, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:157: mismatch in result 0 of assert_return: expected i64:67305985, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:160: mismatch in result 0 of assert_return: expected i64:67305985, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:163: mismatch in result 0 of assert_return: expected i64:84148994, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:166: mismatch in result 0 of assert_return: expected i64:84148994, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:169: mismatch in result 0 of assert_return: expected i64:84148994, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:172: mismatch in result 0 of assert_return: expected i64:100992003, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:175: mismatch in result 0 of assert_return: expected i64:100992003, got i64:0
  +out/test/spec/simd/simd_store32_lane.wast:178: mismatch in result 0 of assert_return: expected i64:100992003, got i64:0
   out/test/spec/simd/simd_store32_lane.wast:183: assert_invalid passed:
     error: type mismatch in v128.store32_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdStoreLaneExpr callback failed
  @@ -7,4 +27,4 @@
   out/test/spec/simd/simd_store32_lane.wast:196: assert_invalid passed:
     error: alignment must not be larger than natural alignment (4)
     0000027: error: OnSimdStoreLaneExpr callback failed
  -23/23 tests passed.
  +3/23 tests passed.
- test/spec/simd/simd_store64_lane.txt
  expected error code 0, got 12.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,15 @@
  +out/test/spec/simd/simd_store64_lane.wast:79: mismatch in result 0 of assert_return: expected i64:506097522914230528, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:82: mismatch in result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:85: mismatch in result 0 of assert_return: expected i64:506097522914230528, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:87: mismatch in result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:89: mismatch in result 0 of assert_return: expected i64:506097522914230528, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:92: mismatch in result 0 of assert_return: expected i64:506097522914230528, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:95: mismatch in result 0 of assert_return: expected i64:506097522914230528, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:98: mismatch in result 0 of assert_return: expected i64:506097522914230528, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:101: mismatch in result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:104: mismatch in result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:107: mismatch in result 0 of assert_return: expected i64:578437695752307201, got i64:0
  +out/test/spec/simd/simd_store64_lane.wast:110: mismatch in result 0 of assert_return: expected i64:578437695752307201, got i64:0
   out/test/spec/simd/simd_store64_lane.wast:115: assert_invalid passed:
     error: type mismatch in v128.store64_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdStoreLaneExpr callback failed
  @@ -7,4 +19,4 @@
   out/test/spec/simd/simd_store64_lane.wast:128: assert_invalid passed:
     error: alignment must not be larger than natural alignment (8)
     0000027: error: OnSimdStoreLaneExpr callback failed
  -15/15 tests passed.
  +3/15 tests passed.
- test/spec/simd/simd_store8_lane.txt
  expected error code 0, got 45.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1,3 +1,48 @@
  +out/test/spec/simd/simd_store8_lane.wast:284: mismatch in result 0 of assert_return: expected i64:1, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:287: mismatch in result 0 of assert_return: expected i64:2, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:290: mismatch in result 0 of assert_return: expected i64:3, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:293: mismatch in result 0 of assert_return: expected i64:4, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:296: mismatch in result 0 of assert_return: expected i64:5, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:299: mismatch in result 0 of assert_return: expected i64:6, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:302: mismatch in result 0 of assert_return: expected i64:7, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:305: mismatch in result 0 of assert_return: expected i64:8, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:308: mismatch in result 0 of assert_return: expected i64:9, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:311: mismatch in result 0 of assert_return: expected i64:10, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:314: mismatch in result 0 of assert_return: expected i64:11, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:317: mismatch in result 0 of assert_return: expected i64:12, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:320: mismatch in result 0 of assert_return: expected i64:13, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:323: mismatch in result 0 of assert_return: expected i64:14, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:326: mismatch in result 0 of assert_return: expected i64:15, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:331: mismatch in result 0 of assert_return: expected i64:1, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:333: mismatch in result 0 of assert_return: expected i64:2, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:335: mismatch in result 0 of assert_return: expected i64:3, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:337: mismatch in result 0 of assert_return: expected i64:4, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:339: mismatch in result 0 of assert_return: expected i64:5, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:341: mismatch in result 0 of assert_return: expected i64:6, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:343: mismatch in result 0 of assert_return: expected i64:7, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:345: mismatch in result 0 of assert_return: expected i64:8, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:347: mismatch in result 0 of assert_return: expected i64:9, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:349: mismatch in result 0 of assert_return: expected i64:10, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:351: mismatch in result 0 of assert_return: expected i64:11, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:353: mismatch in result 0 of assert_return: expected i64:12, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:355: mismatch in result 0 of assert_return: expected i64:13, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:357: mismatch in result 0 of assert_return: expected i64:14, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:359: mismatch in result 0 of assert_return: expected i64:15, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:364: mismatch in result 0 of assert_return: expected i64:1, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:367: mismatch in result 0 of assert_return: expected i64:2, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:370: mismatch in result 0 of assert_return: expected i64:3, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:373: mismatch in result 0 of assert_return: expected i64:4, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:376: mismatch in result 0 of assert_return: expected i64:5, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:379: mismatch in result 0 of assert_return: expected i64:6, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:382: mismatch in result 0 of assert_return: expected i64:7, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:385: mismatch in result 0 of assert_return: expected i64:8, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:388: mismatch in result 0 of assert_return: expected i64:9, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:391: mismatch in result 0 of assert_return: expected i64:10, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:394: mismatch in result 0 of assert_return: expected i64:11, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:397: mismatch in result 0 of assert_return: expected i64:12, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:400: mismatch in result 0 of assert_return: expected i64:13, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:403: mismatch in result 0 of assert_return: expected i64:14, got i64:0
  +out/test/spec/simd/simd_store8_lane.wast:406: mismatch in result 0 of assert_return: expected i64:15, got i64:0
   out/test/spec/simd/simd_store8_lane.wast:411: assert_invalid passed:
     error: type mismatch in v128.store8_lane, expected [i32, v128] but got [v128, i32]
     0000027: error: OnSimdStoreLaneExpr callback failed
  @@ -7,4 +52,4 @@
   out/test/spec/simd/simd_store8_lane.wast:424: assert_invalid passed:
     error: alignment must not be larger than natural alignment (1)
     0000027: error: OnSimdStoreLaneExpr callback failed
  -51/51 tests passed.
  +6/51 tests passed.
[...]
```

**Comment by tlively** [comment]
@ngzhian, could this be the result of a byte order dependency in your recent SIMD work?

**Comment by ngzhian** [comment]
Definitely possible. I don't have easy access to run tests on big endian machines. It does look like we take care of endianess in the interpreter though https://github.com/WebAssembly/wabt/blob/6bc09acabcc7ded2ce934613a7ded98a25217d09/src/interp/interp.h

**Comment by ngzhian** [comment]
@rathann can you help to run the tests on a BE machine to verify that this is fixed?

**Comment by rathann** [comment]
@ngzhian I can confirm that #1697 fixes all test failures on s390x arch for me. Thank you!

Any progress on #1045, #1044 and #1365 ? The failures are still reproducible with 1.0.23.

**Comment by ngzhian** [comment]
I am not actively working on those right now, I'll close this issue as this is fixed, thanks for helping to verify!
