### ISSUE TITLE
import accepts (param i32 i32) but not (param i32) (param i32)

### ISSUE THREAD

**Issue by kevinbarabash** [WebAssembly/wabt#493]
I was following https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format which suggests using the following syntax for an imported function with two i32 params:
```
(import "console" "log" (func $log (param i32) (param i32)))
```
But I get the error
```
test.wast:3:62: syntax error, unexpected PARAM, expecting RESULT
  (import "console" "log" (func $log (param i32) (param i32)))
                                                  ^^^^^
```
I was able to get `wabt` to accept:
```
(import "console" "log" (func $log (param i32 i32)))
```
but it would be nice if the longer version worked as well.

**Comment by binji** [comment]
I believe this was actually fixed in the most recent commit: https://github.com/WebAssembly/wabt/commit/3377747c3fb159826c5bd6d4a70ee5e167c79552. At least this particular example works for me now.

**Comment by kevinbarabash** [comment]
I updated my copy of the `wabt` repo and ran `make` to rebuild the tools, but am still getting the same error.

**Comment by binji** [comment]
Here's my test case:
```
$ cat test.wast
(module (import "console" "log" (func $log (param i32) (param i32))))
$ out/clang/Debug/wast2wasm test.wast -v
0000000: 0061 736d                                 ; WASM_BINARY_MAGIC
0000004: 0100 0000                                 ; WASM_BINARY_VERSION
; section "Type" (1)
0000008: 01                                        ; section code
0000009: 00                                        ; section size (guess)
000000a: 01                                        ; num types
; type 0
000000b: 60                                        ; func
000000c: 02                                        ; num params
000000d: 7f                                        ; i32
000000e: 7f                                        ; i32
000000f: 00                                        ; num results
0000009: 06                                        ; FIXUP section size
; section "Import" (2)
0000010: 02                                        ; section code
0000011: 00                                        ; section size (guess)
0000012: 01                                        ; num imports
; import header 0
0000013: 07                                        ; string length
0000014: 636f 6e73 6f6c 65                        console  ; import module name
000001b: 03                                        ; string length
000001c: 6c6f 67                                  log  ; import field name
000001f: 00                                        ; import kind
0000020: 00                                        ; import signature index
0000011: 0f                                        ; FIXUP section size
```

**Comment by kevinbarabash** [comment]
Running `out/clang/Debug/wast2wasm test.wast -v` works but `bin/wast2wasm test.wast -v` does not.  So I delete the `out` and `bin` folders and ran `make` again.  I forget how I generate the files in `bin` in the first place but running `make` doesn't recreate them.  Anyway, not a big deal, I can call `wast2wasm` from `out/clang/Debug` easily enough.  Thanks for helping me.

**Comment by binji** [comment]
Oh, sorry. `make install` will install to the `bin` directory. This defaults to the clang debug build, but the same is true for `make gcc-debug` => `make install-gcc-debug`, etc.
